# Generated by Django 5.1.4 on 2025-12-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerDemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dealership_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('policy_type', models.CharField(max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InsuranceRenewal',
        ),
        migrations.DeleteModel(
            name='PDIInspection',
        ),
        migrations.RenameField(
            model_name='loanrequest',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='make',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='model',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='sellrequest',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='sellrequest',
            name='year',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='first_name',
            field=models.CharField(default='Guest', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='last_name',
            field=models.CharField(default='User', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='employment_type',
            field=models.CharField(default='Salaried', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='name',
            field=models.CharField(default='Seller', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='ownership',
            field=models.CharField(default='1st', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='reg_number',
            field=models.CharField(default='TEMP001', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='reg_year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='transmission',
            field=models.CharField(default='Manual', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='km_driven',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='variant',
            field=models.CharField(default='VXI', max_length=100),
            preserve_default=False,
        ),
    ]
