# Generated by Django 5.1.4 on 2025-12-11 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.IntegerField()),
                ('status', models.CharField(default='For Sale', max_length=50)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('img_front', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('img_back', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('img_left', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('img_right', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('img_interior_1', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('img_interior_2', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
                ('km_driven', models.IntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.marketplaceuser')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.vehicle')),
            ],
        ),
    ]
