# Generated by Django 5.1.4 on 2025-12-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('4w', '4w'), ('2w', '2w')], default='4w', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='hypothecation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_back_left',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_back_right',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_dashboard',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_engine',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_front_left',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_front_right',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_apron_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_apron_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_apron_leg_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_apron_leg_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_battery',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_bonnet',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_bumper',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_coolant',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_cowl_top',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_door_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_door_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_door_3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_door_4',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_engine_assembly',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_engine_oil',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_firewall',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_pillar_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_pillar_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_pillar_3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_pillar_4',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_pillar_5',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_pillar_6',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_noc',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/docs/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_open_bonnet',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_open_dickey',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_rc',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/docs/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_right_back_door',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_right_front_door',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_roof',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_tyre_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/tyres/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_tyre_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/tyres/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_tyre_3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/tyres/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_tyre_4',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/tyres/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_tyre_optional',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/tyres/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inspection_report',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mfg_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reg_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reg_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rto_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Commercial', 'Commercial')], default='Private', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='video_insp_blowby',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/videos/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='video_insp_engine_smoke',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/videos/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='video_insp_engine_sound',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/videos/'),
        ),
    ]
