# Generated by Django 5.1.4 on 2025-12-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_vehicle_category_vehicle_chassis_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_dickey_door',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_engine_oil_level',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_fender',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_fog_lights_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_fog_lights_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_front_show',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_lights_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_lights_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_lower_cross_member',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_orvm_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_orvm_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_quarter_panel',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_roof',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_upper_cross_member',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='img_insp_windshield',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/inspection/'),
        ),
    ]
