# Generated by Django 5.1.4 on 2025-12-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('lead_type', models.CharField(default='Customer', max_length=50)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=50)),
                ('assigned_to_id', models.CharField(default='Unassigned', max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('dealer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('car_year', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
